DROP TABLE IF EXISTS STOCK;
CREATE  TABLE STOCK(
    ID VARCHAR(100) NOT NULL,
    CATNO VARCHAR(1000),
    AMOUNT INTEGER,
    SYAMOUNT INTEGER,
    COSTPRICE DECIMAL,
    SELLPRICE DECIMAL,
    STOCKTYPE VARCHAR(1000),
    DATETIMED DATE,
    COSTTOTAL DECIMAL,
    STOCKNAME VARCHAR(1000),
    STOCKFLAG VARCHAR(10),
    COLOR VARCHAR(100),
    SPECIF VARCHAR(100), 
    RECORD DATE
);
DROP TABLE IF EXISTS FLOW_LOG;
CREATE  TABLE FLOW_LOG(
    FLOWNO VARCHAR(100), 
    CATNO VARCHAR(1000),
    AMOUNT INTEGER,
    SELLPRICE DECIMAL,
    LRPRICE DECIMAL,
    COSTPRICE DECIMAL,
    STOCKTYPE VARCHAR(1000),
    DATETIMED DATE,
    STOCKNAME VARCHAR(1000),
    FLOWFLAG VARCHAR(10),
    RECORD DATE,
    CUSTOMID VARCHAR(20),
    CUSTOMNAME VARCHAR(20),
);
DROP TABLE IF EXISTS CUSTOM;
CREATE  TABLE CUSTOM(
    CUSTOMID VARCHAR(20),
    CUSTOMNAME VARCHAR(50) ,
    CUSTOMTYPE VARCHAR(50) ,
    SEX VARCHAR(8),
    BIRTHDAY DATE,
    INTEGRATION DOUBLE,
    AMOUNT DECIMAL,
    FREQUENCY INTEGER,
    TELEPHONE VARCHAR(20),
    ADDRESS VARCHAR(200),
    NODTE VARCHAR(2000),
    REGDATE DATE
);
DROP TABLE IF EXISTS CUSTOMTYPE;
CREATE  TABLE CUSTOMTYPE(
    CUSTOMNAME VARCHAR(50) ,
    INTEGRATION DOUBLE ,
    DISCOUNT DOUBLE
);

DROP TABLE IF EXISTS USERRIGHTS ;
CREATE  TABLE USERRIGHTS(
    USERNAME VARCHAR(250) ,
    RIGHTS VARCHAR(100)
);

DROP TABLE IF EXISTS USERS;
CREATE  TABLE USERS(
    USERID VARCHAR(20) ,
    USERNAME VARCHAR(250) ,
    USERTYPE VARCHAR(10),
    PASSWORD VARCHAR(10)
);
INSERT INTO USERS VALUES ( '10000','管理员','Manage','')

DROP TABLE IF EXISTS CONFIG;
CREATE  TABLE CONFIG(
    KEYID VARCHAR(255),
    TEXTVALUE VARCHAR(255)
);
DROP TABLE IF EXISTS OPTIONS;
CREATE  TABLE OPTIONS(
    KEYID VARCHAR(100),
    TEXTVALUE VARCHAR(1000) ,
    OTYPE VARCHAR(10)
);

DROP TABLE IF EXISTS DAILYEXPENSES;
CREATE TABLE DAILYEXPENSES(
  ID VARCHAR(100) PRIMARY KEY,
  ETYPE VARCHAR(500),
  EDATE DATE,
  PAY DECIMAL,
  RECORD DATE
);
